### ISSUE TITLE
Rotating maps creates destroyes the arc position and projection.

### ISSUE THREAD

**Issue by Attique033** [amalChandran/trail-android#29]
By projection i mean the light gray line between start and end below arc.

Can you add some more customizations like arc height, animation duration,  and color or arc projection.

**Comment by Attique033** [comment]
@amalChandran when we can expect this fix in release version? you mentioned this issues is fixed in other branch, can you make it available in release

**Comment by zulqarnainmmmtechltd** [comment]
Hello. rotate map issue is not fixed. Can you please fix it and make release. Also one more thing in this lib we need more than > 2 lat/lon to draw path or arc, it will be very help full if make it for at least 2 locations. so we can draw arc only between 2 location. Thanks.
